.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. harzcoin_qt test_harzcoin_qt
clean: FORCE
	$(MAKE) -C .. harzcoin_qt_clean test_harzcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_harzcoin_qt_check
harzcoin-qt harzcoin-qt.exe: FORCE
	 $(MAKE) -C .. harzcoin_qt
